version: '3.9'

services:
  db:
    image: postgres:16
    container_name: my_skincare
    restart: always
    ports:
      - "5584:5432"  # Host:5584 → Container:5432 (PostgreSQL default)
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: skinCare
    volumes:
      - ./postgres:/var/lib/postgresql/data